import Navbar from "@/components/Navbar/Navbar";
import "../styles/globals.css";
import { AuthProvider } from "contexts/authContext";
import { CartProvider } from "contexts/CartContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CartProvider>
      <AuthProvider>
        <html lang="en">
          <body>
            <Navbar />
            <main>{children}</main>
          </body>
        </html>
      </AuthProvider>
    </CartProvider>
  );
}
